/* Automatically generated by wasm2c */
#ifndef DOTNET_WASM2C_H_GENERATED_
#define DOTNET_WASM2C_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;
struct w2c_wasi__snapshot__preview1;

typedef struct w2c_dotnet {
  struct w2c_env* w2c_env_instance;
  struct w2c_wasi__snapshot__preview1* w2c_wasi__snapshot__preview1_instance;
  u32 w2c_g0;
  u32 w2c_g1;
  u32 w2c_g2;
  wasm_rt_memory_t w2c_memory;
  wasm_rt_funcref_table_t w2c_0x5F_indirect_function_table;
} w2c_dotnet;

void wasm2c_dotnet_instantiate(w2c_dotnet*, struct w2c_env*, struct w2c_wasi__snapshot__preview1*);
void wasm2c_dotnet_free(w2c_dotnet*);
wasm_rt_func_type_t wasm2c_dotnet_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' '__assert_fail' */
void w2c_env_0x5F_assert_fail(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' '__cxa_allocate_exception' */
u32 w2c_env_0x5F_cxa_allocate_exception(struct w2c_env*, u32);

/* import: 'env' '__cxa_begin_catch' */
u32 w2c_env_0x5F_cxa_begin_catch(struct w2c_env*, u32);

/* import: 'env' '__cxa_end_catch' */
void w2c_env_0x5F_cxa_end_catch(struct w2c_env*);

/* import: 'env' '__cxa_find_matching_catch_2' */
u32 w2c_env_0x5F_cxa_find_matching_catch_2(struct w2c_env*);

/* import: 'env' '__cxa_find_matching_catch_3' */
u32 w2c_env_0x5F_cxa_find_matching_catch_3(struct w2c_env*, u32);

/* import: 'env' '__cxa_free_exception' */
void w2c_env_0x5F_cxa_free_exception(struct w2c_env*, u32);

/* import: 'env' '__cxa_rethrow' */
void w2c_env_0x5F_cxa_rethrow(struct w2c_env*);

/* import: 'env' '__cxa_throw' */
void w2c_env_0x5F_cxa_throw(struct w2c_env*, u32, u32, u32);

/* import: 'env' '__resumeException' */
void w2c_env_0x5F_resumeException(struct w2c_env*, u32);

/* import: 'env' '__syscall_faccessat' */
u32 w2c_env_0x5F_syscall_faccessat(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' '__syscall_fadvise64' */
u32 w2c_env_0x5F_syscall_fadvise64(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' '__syscall_fcntl64' */
u32 w2c_env_0x5F_syscall_fcntl64(struct w2c_env*, u32, u32, u32);

/* import: 'env' '__syscall_fstat64' */
u32 w2c_env_0x5F_syscall_fstat64(struct w2c_env*, u32, u32);

/* import: 'env' '__syscall_fstatfs64' */
u32 w2c_env_0x5F_syscall_fstatfs64(struct w2c_env*, u32, u32, u32);

/* import: 'env' '__syscall_ftruncate64' */
u32 w2c_env_0x5F_syscall_ftruncate64(struct w2c_env*, u32, u32, u32);

/* import: 'env' '__syscall_getcwd' */
u32 w2c_env_0x5F_syscall_getcwd(struct w2c_env*, u32, u32);

/* import: 'env' '__syscall_getdents64' */
u32 w2c_env_0x5F_syscall_getdents64(struct w2c_env*, u32, u32, u32);

/* import: 'env' '__syscall_ioctl' */
u32 w2c_env_0x5F_syscall_ioctl(struct w2c_env*, u32, u32, u32);

/* import: 'env' '__syscall_lstat64' */
u32 w2c_env_0x5F_syscall_lstat64(struct w2c_env*, u32, u32);

/* import: 'env' '__syscall_newfstatat' */
u32 w2c_env_0x5F_syscall_newfstatat(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' '__syscall_openat' */
u32 w2c_env_0x5F_syscall_openat(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' '__syscall_readlinkat' */
u32 w2c_env_0x5F_syscall_readlinkat(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' '__syscall_stat64' */
u32 w2c_env_0x5F_syscall_stat64(struct w2c_env*, u32, u32);

/* import: 'env' '__syscall_unlinkat' */
u32 w2c_env_0x5F_syscall_unlinkat(struct w2c_env*, u32, u32, u32);

/* import: 'env' '_emscripten_date_now' */
f64 w2c_env_0x5Femscripten_date_now(struct w2c_env*);

/* import: 'env' '_emscripten_get_now_is_monotonic' */
u32 w2c_env_0x5Femscripten_get_now_is_monotonic(struct w2c_env*);

/* import: 'env' '_localtime_js' */
void w2c_env_0x5Flocaltime_js(struct w2c_env*, u32, u32);

/* import: 'env' '_mmap_js' */
u32 w2c_env_0x5Fmmap_js(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' '_munmap_js' */
u32 w2c_env_0x5Fmunmap_js(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' '_tzset_js' */
void w2c_env_0x5Ftzset_js(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'abort' */
void w2c_env_abort(struct w2c_env*);

/* import: 'env' 'dotnet_browser_entropy' */
u32 w2c_env_dotnet_browser_entropy(struct w2c_env*, u32, u32);

/* import: 'env' 'emscripten_get_heap_max' */
u32 w2c_env_emscripten_get_heap_max(struct w2c_env*);

/* import: 'env' 'emscripten_get_now' */
f64 w2c_env_emscripten_get_now(struct w2c_env*);

/* import: 'env' 'emscripten_get_now_res' */
f64 w2c_env_emscripten_get_now_res(struct w2c_env*);

/* import: 'env' 'emscripten_memcpy_big' */
void w2c_env_emscripten_memcpy_big(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'emscripten_resize_heap' */
u32 w2c_env_emscripten_resize_heap(struct w2c_env*, u32);

/* import: 'env' 'exit' */
void w2c_env_exit(struct w2c_env*, u32);

/* import: 'env' 'getTempRet0' */
u32 w2c_env_getTempRet0(struct w2c_env*);

/* import: 'env' 'invoke_dii' */
f64 w2c_env_invoke_dii(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'invoke_diii' */
f64 w2c_env_invoke_diii(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'invoke_ffii' */
f32 w2c_env_invoke_ffii(struct w2c_env*, u32, f32, u32, u32);

/* import: 'env' 'invoke_ffiii' */
f32 w2c_env_invoke_ffiii(struct w2c_env*, u32, f32, u32, u32, u32);

/* import: 'env' 'invoke_fifi' */
f32 w2c_env_invoke_fifi(struct w2c_env*, u32, u32, f32, u32);

/* import: 'env' 'invoke_fii' */
f32 w2c_env_invoke_fii(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'invoke_fiii' */
f32 w2c_env_invoke_fiii(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'invoke_i' */
u32 w2c_env_invoke_i(struct w2c_env*, u32);

/* import: 'env' 'invoke_ifi' */
u32 w2c_env_invoke_ifi(struct w2c_env*, u32, f32, u32);

/* import: 'env' 'invoke_ii' */
u32 w2c_env_invoke_ii(struct w2c_env*, u32, u32);

/* import: 'env' 'invoke_iidi' */
u32 w2c_env_invoke_iidi(struct w2c_env*, u32, u32, f64, u32);

/* import: 'env' 'invoke_iifi' */
u32 w2c_env_invoke_iifi(struct w2c_env*, u32, u32, f32, u32);

/* import: 'env' 'invoke_iii' */
u32 w2c_env_invoke_iii(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'invoke_iiifi' */
u32 w2c_env_invoke_iiifi(struct w2c_env*, u32, u32, u32, f32, u32);

/* import: 'env' 'invoke_iiifii' */
u32 w2c_env_invoke_iiifii(struct w2c_env*, u32, u32, u32, f32, u32, u32);

/* import: 'env' 'invoke_iiii' */
u32 w2c_env_invoke_iiii(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'invoke_iiiifii' */
u32 w2c_env_invoke_iiiifii(struct w2c_env*, u32, u32, u32, u32, f32, u32, u32);

/* import: 'env' 'invoke_iiiii' */
u32 w2c_env_invoke_iiiii(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_iiiiifi' */
u32 w2c_env_invoke_iiiiifi(struct w2c_env*, u32, u32, u32, u32, u32, f32, u32);

/* import: 'env' 'invoke_iiiiii' */
u32 w2c_env_invoke_iiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_iiiiiii' */
u32 w2c_env_invoke_iiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_iiiiiiii' */
u32 w2c_env_invoke_iiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_iiiiiiiii' */
u32 w2c_env_invoke_iiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_iiiiiiiiiii' */
u32 w2c_env_invoke_iiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_iiiiiiijiii' */
u32 w2c_env_invoke_iiiiiiijiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_iiiiiiji' */
u32 w2c_env_invoke_iiiiiiji(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_iiiji' */
u32 w2c_env_invoke_iiiji(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_iiji' */
u32 w2c_env_invoke_iiji(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_jii' */
u32 w2c_env_invoke_jii(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'invoke_jiii' */
u32 w2c_env_invoke_jiii(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'invoke_jiiii' */
u32 w2c_env_invoke_jiiii(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_jijii' */
u32 w2c_env_invoke_jijii(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_v' */
void w2c_env_invoke_v(struct w2c_env*, u32);

/* import: 'env' 'invoke_vi' */
void w2c_env_invoke_vi(struct w2c_env*, u32, u32);

/* import: 'env' 'invoke_vidi' */
void w2c_env_invoke_vidi(struct w2c_env*, u32, u32, f64, u32);

/* import: 'env' 'invoke_vidii' */
void w2c_env_invoke_vidii(struct w2c_env*, u32, u32, f64, u32, u32);

/* import: 'env' 'invoke_vifi' */
void w2c_env_invoke_vifi(struct w2c_env*, u32, u32, f32, u32);

/* import: 'env' 'invoke_vifii' */
void w2c_env_invoke_vifii(struct w2c_env*, u32, u32, f32, u32, u32);

/* import: 'env' 'invoke_vii' */
void w2c_env_invoke_vii(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'invoke_viidi' */
void w2c_env_invoke_viidi(struct w2c_env*, u32, u32, u32, f64, u32);

/* import: 'env' 'invoke_viifi' */
void w2c_env_invoke_viifi(struct w2c_env*, u32, u32, u32, f32, u32);

/* import: 'env' 'invoke_viii' */
void w2c_env_invoke_viii(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiii' */
void w2c_env_invoke_viiii(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiii' */
void w2c_env_invoke_viiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiidi' */
void w2c_env_invoke_viiiiidi(struct w2c_env*, u32, u32, u32, u32, u32, u32, f64, u32);

/* import: 'env' 'invoke_viiiiii' */
void w2c_env_invoke_viiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiii' */
void w2c_env_invoke_viiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiii' */
void w2c_env_invoke_viiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiii' */
void w2c_env_invoke_viiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii' */
void w2c_env_invoke_viiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viiji' */
void w2c_env_invoke_viiji(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viijiiii' */
void w2c_env_invoke_viijiiii(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viijji' */
void w2c_env_invoke_viijji(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_viji' */
void w2c_env_invoke_viji(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_vijii' */
void w2c_env_invoke_vijii(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'invoke_vijiiiji' */
void w2c_env_invoke_vijiiiji(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'llvm_eh_typeid_for' */
u32 w2c_env_llvm_eh_typeid_for(struct w2c_env*, u32);

/* import: 'env' 'mono_set_timeout' */
void w2c_env_mono_set_timeout(struct w2c_env*, u32);

/* import: 'env' 'mono_wasm_bind_cs_function' */
void w2c_env_mono_wasm_bind_cs_function(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_bind_js_function' */
void w2c_env_mono_wasm_bind_js_function(struct w2c_env*, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_create_cs_owned_object_ref' */
void w2c_env_mono_wasm_create_cs_owned_object_ref(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_get_by_index_ref' */
void w2c_env_mono_wasm_get_by_index_ref(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_get_global_object_ref' */
void w2c_env_mono_wasm_get_global_object_ref(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'mono_wasm_get_object_property_ref' */
void w2c_env_mono_wasm_get_object_property_ref(struct w2c_env*, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_invoke_bound_function' */
void w2c_env_mono_wasm_invoke_bound_function(struct w2c_env*, u32, u32);

/* import: 'env' 'mono_wasm_invoke_js_blazor' */
u32 w2c_env_mono_wasm_invoke_js_blazor(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_invoke_js_with_args_ref' */
void w2c_env_mono_wasm_invoke_js_with_args_ref(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_marshal_promise' */
void w2c_env_mono_wasm_marshal_promise(struct w2c_env*, u32);

/* import: 'env' 'mono_wasm_release_cs_owned_object' */
void w2c_env_mono_wasm_release_cs_owned_object(struct w2c_env*, u32);

/* import: 'env' 'mono_wasm_set_by_index_ref' */
void w2c_env_mono_wasm_set_by_index_ref(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_set_entrypoint_breakpoint' */
void w2c_env_mono_wasm_set_entrypoint_breakpoint(struct w2c_env*, u32, u32);

/* import: 'env' 'mono_wasm_set_object_property_ref' */
void w2c_env_mono_wasm_set_object_property_ref(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_trace_logger' */
void w2c_env_mono_wasm_trace_logger(struct w2c_env*, u32, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_typed_array_from_ref' */
void w2c_env_mono_wasm_typed_array_from_ref(struct w2c_env*, u32, u32, u32, u32, u32, u32, u32);

/* import: 'env' 'mono_wasm_typed_array_to_array_ref' */
void w2c_env_mono_wasm_typed_array_to_array_ref(struct w2c_env*, u32, u32, u32);

/* import: 'env' 'schedule_background_exec' */
void w2c_env_schedule_background_exec(struct w2c_env*);

/* import: 'env' 'setTempRet0' */
void w2c_env_setTempRet0(struct w2c_env*, u32);

/* import: 'env' 'strftime' */
u32 w2c_env_strftime(struct w2c_env*, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'environ_get' */
u32 w2c_wasi__snapshot__preview1_environ_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'environ_sizes_get' */
u32 w2c_wasi__snapshot__preview1_environ_sizes_get(struct w2c_wasi__snapshot__preview1*, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_close' */
u32 w2c_wasi__snapshot__preview1_fd_close(struct w2c_wasi__snapshot__preview1*, u32);

/* import: 'wasi_snapshot_preview1' 'fd_pread' */
u32 w2c_wasi__snapshot__preview1_fd_pread(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_pwrite' */
u32 w2c_wasi__snapshot__preview1_fd_pwrite(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_read' */
u32 w2c_wasi__snapshot__preview1_fd_read(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_seek' */
u32 w2c_wasi__snapshot__preview1_fd_seek(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32, u32);

/* import: 'wasi_snapshot_preview1' 'fd_sync' */
u32 w2c_wasi__snapshot__preview1_fd_sync(struct w2c_wasi__snapshot__preview1*, u32);

/* import: 'wasi_snapshot_preview1' 'fd_write' */
u32 w2c_wasi__snapshot__preview1_fd_write(struct w2c_wasi__snapshot__preview1*, u32, u32, u32, u32);

/* export: 'memory' */
wasm_rt_memory_t* w2c_dotnet_memory(w2c_dotnet* instance);

/* export: '__wasm_call_ctors' */
void w2c_dotnet_0x5F_wasm_call_ctors(w2c_dotnet*);

/* export: 'memset' */
u32 w2c_dotnet_memset(w2c_dotnet*, u32, u32, u32);

/* export: 'mono_aot_Microsoft_JSInterop_get_method' */
u32 w2c_dotnet_mono_aot_Microsoft_JSInterop_get_method(w2c_dotnet*, u32);

/* export: '__indirect_function_table' */
wasm_rt_funcref_table_t* w2c_dotnet_0x5F_indirect_function_table(w2c_dotnet* instance);

/* export: 'mono_aot_DCSoft_WASM_get_method' */
u32 w2c_dotnet_mono_aot_DCSoft_WASM_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Collections_Concurrent_get_method' */
u32 w2c_dotnet_mono_aot_System_Collections_Concurrent_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Collections_NonGeneric_get_method' */
u32 w2c_dotnet_mono_aot_System_Collections_NonGeneric_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Collections_Specialized_get_method' */
u32 w2c_dotnet_mono_aot_System_Collections_Specialized_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Collections_get_method' */
u32 w2c_dotnet_mono_aot_System_Collections_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_ComponentModel_Primitives_get_method' */
u32 w2c_dotnet_mono_aot_System_ComponentModel_Primitives_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_ComponentModel_TypeConverter_get_method' */
u32 w2c_dotnet_mono_aot_System_ComponentModel_TypeConverter_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_ComponentModel_get_method' */
u32 w2c_dotnet_mono_aot_System_ComponentModel_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_IO_Compression_get_method' */
u32 w2c_dotnet_mono_aot_System_IO_Compression_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Linq_get_method' */
u32 w2c_dotnet_mono_aot_System_Linq_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Memory_get_method' */
u32 w2c_dotnet_mono_aot_System_Memory_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Net_Http_get_method' */
u32 w2c_dotnet_mono_aot_System_Net_Http_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Net_Primitives_get_method' */
u32 w2c_dotnet_mono_aot_System_Net_Primitives_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_ObjectModel_get_method' */
u32 w2c_dotnet_mono_aot_System_ObjectModel_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Private_Uri_get_method' */
u32 w2c_dotnet_mono_aot_System_Private_Uri_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Private_Xml_get_method' */
u32 w2c_dotnet_mono_aot_System_Private_Xml_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Runtime_InteropServices_JavaScript_get_method' */
u32 w2c_dotnet_mono_aot_System_Runtime_InteropServices_JavaScript_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Runtime_get_method' */
u32 w2c_dotnet_mono_aot_System_Runtime_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Text_Encodings_Web_get_method' */
u32 w2c_dotnet_mono_aot_System_Text_Encodings_Web_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Text_Json_get_method' */
u32 w2c_dotnet_mono_aot_System_Text_Json_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Text_RegularExpressions_get_method' */
u32 w2c_dotnet_mono_aot_System_Text_RegularExpressions_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Threading_get_method' */
u32 w2c_dotnet_mono_aot_System_Threading_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_Xml_ReaderWriter_get_method' */
u32 w2c_dotnet_mono_aot_System_Xml_ReaderWriter_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_System_get_method' */
u32 w2c_dotnet_mono_aot_System_get_method(w2c_dotnet*, u32);

/* export: 'mono_aot_corlib_get_method' */
u32 w2c_dotnet_mono_aot_corlib_get_method(w2c_dotnet*, u32);

/* export: 'mono_wasm_register_root' */
u32 w2c_dotnet_mono_wasm_register_root(w2c_dotnet*, u32, u32, u32);

/* export: 'mono_wasm_deregister_root' */
void w2c_dotnet_mono_wasm_deregister_root(w2c_dotnet*, u32);

/* export: 'mono_wasm_add_assembly' */
u32 w2c_dotnet_mono_wasm_add_assembly(w2c_dotnet*, u32, u32, u32);

/* export: 'mono_wasm_add_satellite_assembly' */
void w2c_dotnet_mono_wasm_add_satellite_assembly(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'mono_wasm_setenv' */
void w2c_dotnet_mono_wasm_setenv(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_getenv' */
u32 w2c_dotnet_mono_wasm_getenv(w2c_dotnet*, u32);

/* export: 'mono_wasm_register_bundled_satellite_assemblies' */
void w2c_dotnet_mono_wasm_register_bundled_satellite_assemblies(w2c_dotnet*);

/* export: 'free' */
void w2c_dotnet_free(w2c_dotnet*, u32);

/* export: 'mono_wasm_load_runtime' */
void w2c_dotnet_mono_wasm_load_runtime(w2c_dotnet*, u32, u32);

/* export: 'malloc' */
u32 w2c_dotnet_malloc(w2c_dotnet*, u32);

/* export: 'mono_wasm_assembly_load' */
u32 w2c_dotnet_mono_wasm_assembly_load(w2c_dotnet*, u32);

/* export: 'mono_wasm_get_corlib' */
u32 w2c_dotnet_mono_wasm_get_corlib(w2c_dotnet*);

/* export: 'mono_wasm_assembly_find_class' */
u32 w2c_dotnet_mono_wasm_assembly_find_class(w2c_dotnet*, u32, u32, u32);

/* export: 'mono_wasm_runtime_run_module_cctor' */
void w2c_dotnet_mono_wasm_runtime_run_module_cctor(w2c_dotnet*, u32);

/* export: 'mono_wasm_assembly_find_method' */
u32 w2c_dotnet_mono_wasm_assembly_find_method(w2c_dotnet*, u32, u32, u32);

/* export: 'mono_wasm_get_delegate_invoke_ref' */
u32 w2c_dotnet_mono_wasm_get_delegate_invoke_ref(w2c_dotnet*, u32);

/* export: 'mono_wasm_box_primitive_ref' */
void w2c_dotnet_mono_wasm_box_primitive_ref(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'mono_wasm_invoke_method_ref' */
void w2c_dotnet_mono_wasm_invoke_method_ref(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'mono_wasm_invoke_method_bound' */
u32 w2c_dotnet_mono_wasm_invoke_method_bound(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_assembly_get_entry_point' */
u32 w2c_dotnet_mono_wasm_assembly_get_entry_point(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_string_get_utf8' */
u32 w2c_dotnet_mono_wasm_string_get_utf8(w2c_dotnet*, u32);

/* export: 'mono_wasm_string_from_js' */
u32 w2c_dotnet_mono_wasm_string_from_js(w2c_dotnet*, u32);

/* export: 'mono_wasm_string_from_utf16_ref' */
void w2c_dotnet_mono_wasm_string_from_utf16_ref(w2c_dotnet*, u32, u32, u32);

/* export: 'mono_wasm_get_obj_class' */
u32 w2c_dotnet_mono_wasm_get_obj_class(w2c_dotnet*, u32);

/* export: 'mono_wasm_get_obj_type' */
u32 w2c_dotnet_mono_wasm_get_obj_type(w2c_dotnet*, u32);

/* export: 'mono_wasm_try_unbox_primitive_and_get_type_ref' */
u32 w2c_dotnet_mono_wasm_try_unbox_primitive_and_get_type_ref(w2c_dotnet*, u32, u32, u32);

/* export: 'mono_wasm_array_length' */
u32 w2c_dotnet_mono_wasm_array_length(w2c_dotnet*, u32);

/* export: 'mono_wasm_array_get' */
u32 w2c_dotnet_mono_wasm_array_get(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_array_get_ref' */
void w2c_dotnet_mono_wasm_array_get_ref(w2c_dotnet*, u32, u32, u32);

/* export: 'mono_wasm_obj_array_new_ref' */
void w2c_dotnet_mono_wasm_obj_array_new_ref(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_obj_array_new' */
u32 w2c_dotnet_mono_wasm_obj_array_new(w2c_dotnet*, u32);

/* export: 'mono_wasm_obj_array_set' */
void w2c_dotnet_mono_wasm_obj_array_set(w2c_dotnet*, u32, u32, u32);

/* export: 'mono_wasm_obj_array_set_ref' */
void w2c_dotnet_mono_wasm_obj_array_set_ref(w2c_dotnet*, u32, u32, u32);

/* export: 'mono_wasm_string_array_new_ref' */
void w2c_dotnet_mono_wasm_string_array_new_ref(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_exec_regression' */
u32 w2c_dotnet_mono_wasm_exec_regression(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_exit' */
u32 w2c_dotnet_mono_wasm_exit(w2c_dotnet*, u32);

/* export: 'mono_wasm_set_main_args' */
void w2c_dotnet_mono_wasm_set_main_args(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_strdup' */
u32 w2c_dotnet_mono_wasm_strdup(w2c_dotnet*, u32);

/* export: 'mono_wasm_parse_runtime_options' */
void w2c_dotnet_mono_wasm_parse_runtime_options(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_enable_on_demand_gc' */
void w2c_dotnet_mono_wasm_enable_on_demand_gc(w2c_dotnet*, u32);

/* export: 'mono_wasm_intern_string_ref' */
void w2c_dotnet_mono_wasm_intern_string_ref(w2c_dotnet*, u32);

/* export: 'mono_wasm_string_get_data_ref' */
void w2c_dotnet_mono_wasm_string_get_data_ref(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'mono_wasm_string_get_data' */
void w2c_dotnet_mono_wasm_string_get_data(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'mono_wasm_class_get_type' */
u32 w2c_dotnet_mono_wasm_class_get_type(w2c_dotnet*, u32);

/* export: 'mono_wasm_type_get_class' */
u32 w2c_dotnet_mono_wasm_type_get_class(w2c_dotnet*, u32);

/* export: 'mono_wasm_get_type_name' */
u32 w2c_dotnet_mono_wasm_get_type_name(w2c_dotnet*, u32);

/* export: 'mono_wasm_get_type_aqn' */
u32 w2c_dotnet_mono_wasm_get_type_aqn(w2c_dotnet*, u32);

/* export: 'mono_wasm_write_managed_pointer_unsafe' */
void w2c_dotnet_mono_wasm_write_managed_pointer_unsafe(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_copy_managed_pointer' */
void w2c_dotnet_mono_wasm_copy_managed_pointer(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_i52_to_f64' */
f64 w2c_dotnet_mono_wasm_i52_to_f64(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_u52_to_f64' */
f64 w2c_dotnet_mono_wasm_u52_to_f64(w2c_dotnet*, u32, u32);

/* export: 'mono_wasm_f64_to_u52' */
u32 w2c_dotnet_mono_wasm_f64_to_u52(w2c_dotnet*, u32, f64);

/* export: 'mono_wasm_f64_to_i52' */
u32 w2c_dotnet_mono_wasm_f64_to_i52(w2c_dotnet*, u32, f64);

/* export: 'mono_wasm_typed_array_new_ref' */
void w2c_dotnet_mono_wasm_typed_array_new_ref(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'mono_wasm_unbox_enum' */
u32 w2c_dotnet_mono_wasm_unbox_enum(w2c_dotnet*, u32);

/* export: 'mono_wasm_send_dbg_command_with_parms' */
u32 w2c_dotnet_mono_wasm_send_dbg_command_with_parms(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'mono_wasm_send_dbg_command' */
u32 w2c_dotnet_mono_wasm_send_dbg_command(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'mono_wasm_event_pipe_enable' */
u32 w2c_dotnet_mono_wasm_event_pipe_enable(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'mono_wasm_event_pipe_session_start_streaming' */
u32 w2c_dotnet_mono_wasm_event_pipe_session_start_streaming(w2c_dotnet*, u32);

/* export: 'mono_wasm_event_pipe_session_disable' */
u32 w2c_dotnet_mono_wasm_event_pipe_session_disable(w2c_dotnet*, u32);

/* export: '__errno_location' */
u32 w2c_dotnet_0x5F_errno_location(w2c_dotnet*);

/* export: 'mono_background_exec' */
void w2c_dotnet_mono_background_exec(w2c_dotnet*);

/* export: 'mono_wasm_get_icudt_name' */
u32 w2c_dotnet_mono_wasm_get_icudt_name(w2c_dotnet*, u32);

/* export: 'mono_wasm_load_icu_data' */
u32 w2c_dotnet_mono_wasm_load_icu_data(w2c_dotnet*, u32);

/* export: 'mono_print_method_from_ip' */
void w2c_dotnet_mono_print_method_from_ip(w2c_dotnet*, u32);

/* export: 'mono_set_timeout_exec' */
void w2c_dotnet_mono_set_timeout_exec(w2c_dotnet*);

/* export: '__dl_seterr' */
void w2c_dotnet_0x5F_dl_seterr(w2c_dotnet*, u32, u32);

/* export: 'htonl' */
u32 w2c_dotnet_htonl(w2c_dotnet*, u32);

/* export: 'htons' */
u32 w2c_dotnet_htons(w2c_dotnet*, u32);

/* export: 'emscripten_builtin_memalign' */
u32 w2c_dotnet_emscripten_builtin_memalign(w2c_dotnet*, u32, u32);

/* export: 'ntohs' */
u32 w2c_dotnet_ntohs(w2c_dotnet*, u32);

/* export: 'memalign' */
u32 w2c_dotnet_memalign(w2c_dotnet*, u32, u32);

/* export: 'setThrew' */
void w2c_dotnet_setThrew(w2c_dotnet*, u32, u32);

/* export: 'stackSave' */
u32 w2c_dotnet_stackSave(w2c_dotnet*);

/* export: 'stackRestore' */
void w2c_dotnet_stackRestore(w2c_dotnet*, u32);

/* export: 'stackAlloc' */
u32 w2c_dotnet_stackAlloc(w2c_dotnet*, u32);

/* export: '__cxa_can_catch' */
u32 w2c_dotnet_0x5F_cxa_can_catch(w2c_dotnet*, u32, u32, u32);

/* export: '__cxa_is_pointer_type' */
u32 w2c_dotnet_0x5F_cxa_is_pointer_type(w2c_dotnet*, u32);

/* export: 'dynCall_viji' */
void w2c_dotnet_dynCall_viji(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiji' */
u32 w2c_dotnet_dynCall_iiji(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'dynCall_jii' */
u32 w2c_dotnet_dynCall_jii(w2c_dotnet*, u32, u32, u32);

/* export: 'dynCall_iiijii' */
u32 w2c_dotnet_dynCall_iiijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viijiii' */
void w2c_dotnet_dynCall_viijiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viijiiii' */
void w2c_dotnet_dynCall_viijiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iijiii' */
u32 w2c_dotnet_dynCall_iijiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iijii' */
u32 w2c_dotnet_dynCall_iijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jiii' */
u32 w2c_dotnet_dynCall_jiii(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'dynCall_viiijii' */
void w2c_dotnet_dynCall_viiijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viiji' */
void w2c_dotnet_dynCall_viiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viijji' */
void w2c_dotnet_dynCall_viijji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iijiiii' */
u32 w2c_dotnet_dynCall_iijiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iijiiiiii' */
u32 w2c_dotnet_dynCall_iijiiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vijii' */
void w2c_dotnet_dynCall_vijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vji' */
void w2c_dotnet_dynCall_vji(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'dynCall_iiijiii' */
u32 w2c_dotnet_dynCall_iiijiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iijji' */
u32 w2c_dotnet_dynCall_iijji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiijii' */
u32 w2c_dotnet_dynCall_iiiijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiiiji' */
u32 w2c_dotnet_dynCall_iiiiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vijiiiji' */
void w2c_dotnet_dynCall_vijiiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vijiiii' */
void w2c_dotnet_dynCall_vijiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiiijii' */
u32 w2c_dotnet_dynCall_iiiiijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iji' */
u32 w2c_dotnet_dynCall_iji(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'dynCall_ji' */
u32 w2c_dotnet_dynCall_ji(w2c_dotnet*, u32, u32);

/* export: 'dynCall_ijji' */
u32 w2c_dotnet_dynCall_ijji(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jji' */
u32 w2c_dotnet_dynCall_jji(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'dynCall_ijiiii' */
u32 w2c_dotnet_dynCall_ijiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jiiiii' */
u32 w2c_dotnet_dynCall_jiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_ijii' */
u32 w2c_dotnet_dynCall_ijii(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'dynCall_jjiii' */
u32 w2c_dotnet_dynCall_jjiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jjii' */
u32 w2c_dotnet_dynCall_jjii(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'dynCall_vjiii' */
void w2c_dotnet_dynCall_vjiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jijii' */
u32 w2c_dotnet_dynCall_jijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jiiii' */
u32 w2c_dotnet_dynCall_jiiii(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'dynCall_viiiji' */
void w2c_dotnet_dynCall_viiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viiiiji' */
void w2c_dotnet_dynCall_viiiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiji' */
u32 w2c_dotnet_dynCall_iiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jiiifii' */
u32 w2c_dotnet_dynCall_jiiifii(w2c_dotnet*, u32, u32, u32, u32, f32, u32, u32);

/* export: 'dynCall_vijiii' */
void w2c_dotnet_dynCall_vijiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viiijiii' */
void w2c_dotnet_dynCall_viiijiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiiiiji' */
u32 w2c_dotnet_dynCall_iiiiiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vijji' */
void w2c_dotnet_dynCall_vijji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vijjiiiii' */
void w2c_dotnet_dynCall_vijjiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vijjji' */
void w2c_dotnet_dynCall_vijjji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vijjjii' */
void w2c_dotnet_dynCall_vijjjii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viiiiiji' */
void w2c_dotnet_dynCall_viiiiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vjjiiiii' */
void w2c_dotnet_dynCall_vjjiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viijii' */
void w2c_dotnet_dynCall_viijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viiiijii' */
void w2c_dotnet_dynCall_viiiijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viiiiiiji' */
void w2c_dotnet_dynCall_viiiiiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jiji' */
u32 w2c_dotnet_dynCall_jiji(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'dynCall_jijji' */
u32 w2c_dotnet_dynCall_jijji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_diji' */
f64 w2c_dotnet_dynCall_diji(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'dynCall_jidi' */
u32 w2c_dotnet_dynCall_jidi(w2c_dotnet*, u32, u32, f64, u32);

/* export: 'dynCall_ijjji' */
u32 w2c_dotnet_dynCall_ijjji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vijjiii' */
void w2c_dotnet_dynCall_vijjiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_ijiii' */
u32 w2c_dotnet_dynCall_ijiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_ijjiiii' */
u32 w2c_dotnet_dynCall_ijjiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiiiiijiii' */
u32 w2c_dotnet_dynCall_iiiiiiijiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iijjii' */
u32 w2c_dotnet_dynCall_iijjii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiiji' */
u32 w2c_dotnet_dynCall_iiiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jiiiji' */
u32 w2c_dotnet_dynCall_jiiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiiiijiii' */
u32 w2c_dotnet_dynCall_iiiiiijiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiiiijiiiii' */
u32 w2c_dotnet_dynCall_iiiiiijiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jjjii' */
u32 w2c_dotnet_dynCall_jjjii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jjji' */
u32 w2c_dotnet_dynCall_jjji(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jdi' */
u32 w2c_dotnet_dynCall_jdi(w2c_dotnet*, u32, f64, u32);

/* export: 'dynCall_dji' */
f64 w2c_dotnet_dynCall_dji(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'dynCall_jfi' */
u32 w2c_dotnet_dynCall_jfi(w2c_dotnet*, u32, f32, u32);

/* export: 'dynCall_fji' */
f32 w2c_dotnet_dynCall_fji(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'dynCall_jiiiiiiiii' */
u32 w2c_dotnet_dynCall_jiiiiiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viidjji' */
void w2c_dotnet_dynCall_viidjji(w2c_dotnet*, u32, u32, u32, f64, u32, u32, u32, u32, u32);

/* export: 'dynCall_jiiiiii' */
u32 w2c_dotnet_dynCall_jiiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vjjii' */
void w2c_dotnet_dynCall_vjjii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vjii' */
void w2c_dotnet_dynCall_vjii(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'dynCall_ijiiiiiiii' */
u32 w2c_dotnet_dynCall_ijiiiiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_ijiiiii' */
u32 w2c_dotnet_dynCall_ijiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jdii' */
u32 w2c_dotnet_dynCall_jdii(w2c_dotnet*, u32, f64, u32, u32);

/* export: 'dynCall_jijiii' */
u32 w2c_dotnet_dynCall_jijiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vijjii' */
void w2c_dotnet_dynCall_vijjii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiijjjii' */
u32 w2c_dotnet_dynCall_iiijjjii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiijjjjji' */
u32 w2c_dotnet_dynCall_iiijjjjji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viiiiijiiiiiii' */
void w2c_dotnet_dynCall_viiiiijiiiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_vjji' */
void w2c_dotnet_dynCall_vjji(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viiiiiiiji' */
void w2c_dotnet_dynCall_viiiiiiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jiiji' */
u32 w2c_dotnet_dynCall_jiiji(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiiiiiijii' */
u32 w2c_dotnet_dynCall_iiiiiiiijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiiiijii' */
u32 w2c_dotnet_dynCall_iiiiiijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viiiiiijii' */
void w2c_dotnet_dynCall_viiiiiijii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viijjji' */
void w2c_dotnet_dynCall_viijjji(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jd' */
u32 w2c_dotnet_dynCall_jd(w2c_dotnet*, u32, f64);

/* export: 'dynCall_jf' */
u32 w2c_dotnet_dynCall_jf(w2c_dotnet*, u32, f32);

/* export: 'dynCall_vj' */
void w2c_dotnet_dynCall_vj(w2c_dotnet*, u32, u32, u32);

/* export: 'dynCall_ij' */
u32 w2c_dotnet_dynCall_ij(w2c_dotnet*, u32, u32, u32);

/* export: 'dynCall_iij' */
u32 w2c_dotnet_dynCall_iij(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'dynCall_jj' */
u32 w2c_dotnet_dynCall_jj(w2c_dotnet*, u32, u32, u32);

/* export: 'dynCall_iiijiiiii' */
u32 w2c_dotnet_dynCall_iiijiiiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_j' */
u32 w2c_dotnet_dynCall_j(w2c_dotnet*, u32);

/* export: 'dynCall_iijjiii' */
u32 w2c_dotnet_dynCall_iijjiii(w2c_dotnet*, u32, u32, u32, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jij' */
u32 w2c_dotnet_dynCall_jij(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'dynCall_vij' */
void w2c_dotnet_dynCall_vij(w2c_dotnet*, u32, u32, u32, u32);

/* export: 'dynCall_iijj' */
u32 w2c_dotnet_dynCall_iijj(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_iiiij' */
u32 w2c_dotnet_dynCall_iiiij(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_jiiij' */
u32 w2c_dotnet_dynCall_jiiij(w2c_dotnet*, u32, u32, u32, u32, u32, u32);

/* export: 'dynCall_viij' */
void w2c_dotnet_dynCall_viij(w2c_dotnet*, u32, u32, u32, u32, u32);

/* export: 'dynCall_jijj' */
u32 w2c_dotnet_dynCall_jijj